(use-modules (ice-9 regex)
	     (ice-9 rdelim))
;; (define (parse-nat cs acc)
;;   (let ((acc->nat (lambda (a)
;; 		    (string->number (list->string (reverse a))))))
;;     (cond ((null? cs) (list (acc->nat acc)))
;; 	  ((char-set-contains? char-set:digit (car cs))
;; 	   (parse-nat (cdr cs) (cons (car cs) acc)))
;; 	  (else (cons (acc->nat acc) cs)))))
(define marker-regexp (make-regexp "\\(([0-9]+)x([0-9]+)\\)"))

(define (match->marker m)
  (cons (string->number (match:substring m 1))
	(string->number (match:substring m 2))))

(define (iterate-and-count str)
  (let loop ((i 0)
	     (count (string-length str)))

    (let ((m (regexp-exec marker-regexp str i)))
      (if m
	  (let* ((marker-len (string-length (match:substring m 0)))
		 (marker (match->marker m))
		 (len (car marker))
		 (mult (cdr marker)))
	    (loop (+ (match:end m) len)
		  (+ count (* (- mult 1) len) (- marker-len))))
	  count))))

(define (main file)
  (let* ((port (open-file file "r"))
	 (s (read-delimited "\n" port)))
    (close port)
    (iterate-and-count s)))
